/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nativewrapper_cap_CapJni */

#ifndef _Included_com_nativewrapper_cap_CapJni
#define _Included_com_nativewrapper_cap_CapJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nativewrapper_cap_CapJni
 * Method:    nativeInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_nativewrapper_cap_CapJni_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_nativewrapper_cap_CapJni
 * Method:    nativeFin
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_nativewrapper_cap_CapJni_nativeFin
  (JNIEnv *, jobject);

/*
 * Class:     com_nativewrapper_cap_CapJni
 * Method:    nativeSetInterface
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_nativewrapper_cap_CapJni_nativeSetInterface
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_nativewrapper_cap_CapJni
 * Method:    nativeSetFilter
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_nativewrapper_cap_CapJni_nativeSetFilter
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_nativewrapper_cap_CapJni
 * Method:    nativeClearFilter
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_nativewrapper_cap_CapJni_nativeClearFilter
  (JNIEnv *, jobject);

/*
 * Class:     com_nativewrapper_cap_CapJni
 * Method:    nativeStart
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_nativewrapper_cap_CapJni_nativeStart
  (JNIEnv *, jobject);

/*
 * Class:     com_nativewrapper_cap_CapJni
 * Method:    nativeStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_nativewrapper_cap_CapJni_nativeStop
  (JNIEnv *, jobject);

/*
 * Class:     com_nativewrapper_cap_CapJni
 * Method:    nativeRegisterPacketListener
 * Signature: (Lcom/nativewrapper/cap/IPacketListener;)I
 */
JNIEXPORT jint JNICALL Java_com_nativewrapper_cap_CapJni_nativeRegisterPacketListener
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_nativewrapper_cap_CapJni
 * Method:    nativeUnregisterPacketListener
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_nativewrapper_cap_CapJni_nativeUnregisterPacketListener
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_nativewrapper_cap_CapJni
 * Method:    nativeGetInterfaceList
 * Signature: (Ljava/util/List;)I
 */
JNIEXPORT jint JNICALL Java_com_nativewrapper_cap_CapJni_nativeGetInterfaceList
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
